openapi: 3.0.3
info:
  title: Music Rights
  description: API para la gestión y automatización de reclamo de Royalties.
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Servidor Local

paths:
  /claims:
    get:
      summary: Obtener lista de reclamaciones por filtros
      parameters:
        - name: pending
          in: query
          schema:
            type: boolean
        - name: status
          in: query
          schema:
            type: string
        - name: type
          in: query
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Claim'
        '400':
          description: Bad Request. Parámetros de la consulta no válidos.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    post:
      summary: Crear nueva reclamación
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Claim'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Claim'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /claims/{id}:
    get:
      summary: Buscar reclamación por su id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Claim'
        '404':
          description: La reclamación no existe
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    put:
      summary: Modificar reclamación
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Claim'
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: La reclamación no existe
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    delete:
      summary: Eliminar reclamación.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: No Content
        '404':
          description: La reclamación no existe
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /claims/by-musician/{id}:
    get:
      summary: Buscar las reclamaciones de un músico por su id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Claim'
        '404':
          description: El músico no existe
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /concerts:
    get:
      summary: Obtener lista de conciertos por músico
      parameters:
        - name: city
          in: query
          schema:
            type: string
        - name: status
          in: query
          schema:
            type: string
        - name: performed
          in: query
          schema:
            type: boolean
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Concert'
        '400':
          description: Bad Request (Parámetros de consulta inválidos)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    post:
      summary: Crear concierto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Concert'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Concert'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /concerts/{id}:
    get:
      summary: Obetener concierto por id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Concert'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    put:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Concert'
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    delete:
      summary: Eliminar concierto
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /concerts/by-musician/{id}:
    get:
      summary: Obtener conciertos de un músico por id de concierto
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Concert'
        '404':
          description: Musician Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /documents:
    get:
      summary: Obtener lista de documentos por filtrados
      parameters:
        - name: type
          in: query
          schema:
            type: string
        - name: complete
          in: query
          schema:
            type: boolean
        - name: createAd
          in: query
          schema:
            type: string
            format: date
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Document'
        '400':
          description: Bad Request (Parámetros de consulta inválidos)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    post:
      summary: Completar campos documento
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Document'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Document'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /documents/{id}:
    get:
      summary: Obtener documento por id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Document'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    put:
      summary: Modificar documento
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Document'
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    delete:
      summary: Eliminar documento
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /documents/by-claim/{id}:
    get:
      summary: Obtener documento por id de reclamación
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Document'
        '404':
          description: Claim Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /works:
    get:
      summary: Listar obras musicales con opción a 3 filtros
      parameters:
        - name: duration
          in: query
          schema:
            type: number
            format: float
        - name: composedAt
          in: query
          schema:
            type: string
            format: date
        - name: registred
          in: query
          schema:
            type: boolean
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Work'
        '400':
          description: Bad Request (Parámetros de consulta inválidos)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    post:
      summary: Registrar nueva obra
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Work'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Work'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /works/{id}:
    get:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Work'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    put:
      summary: Modificar obra
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Work'
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    delete:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    Work:
      type: object
      required: [ title, isrc, genre, registred ]
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
        title:
          type: string
          minLength: 1
        isrc:
          type: string
          pattern: '^[A-Z]{2}[A-Z0-9]{3}\d{2}\d{5}$'
          example: "ESABC2300123"
          description: "Código único ISRC"
        genre:
          type: string
          minLength: 1
        duration:
          type: number
          format: float
          description: "Duración en segundos/minutos"
          minimum: 0.0
        composedAt:
          type: string
          format: date
          description: "Fecha de composición"
        registred:
          type: boolean
      # Musicians esta ignorado por java por @JsonIgnore

    Musician:
      type: object
      required: [ firstName, lastName, affiliated, dni ]
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
        firstName:
          type: string
        lastName:
          type: string
        birthDate:
          type: string
          format: date
        affiliated:
          type: boolean
        dni:
          type: string
          pattern: '^\d{8}[A-Za-z]$'
          example: "12345678Z"
        performanceFee:
          type: number
          format: float
          minimum: 0.0
        affiliatedNumber:
          type: integer
          format: int64
        works:
          type: array
          items:
            $ref: '#/components/schemas/Work'
      # Claims esta ignorado por java por @JsonIgnore

    Concert:
      type: object
      required: [ city, province, date, performed ]
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
        showTitle:
          type: string
        city:
          type: string
          minLength: 1
        province:
          type: string
          minLength: 1
        date:
          type: string
          format: date
        status:
          type: string
        performed:
          type: boolean
        ticketPrice:
          type: number
          format: float
          minimum: 0.0
        longitude:
          type: number
          format: double
        latitude:
          type: number
          format: double
        musician:
          $ref: '#/components/schemas/Musician'

    Claim:
      type: object
      required: [ reference ]
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
        reference:
          type: string
          minLength: 1
        status:
          type: string
        type:
          type: string
        description:
          type: string
        pending:
          type: boolean
        musician:
          $ref: '#/components/schemas/Musician'

    Document:
      type: object
      required: [ type, filename ]
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
        type:
          type: string
          minLength: 1
        filename:
          type: string
          minLength: 1
        size:
          type: integer
          format: int64
          minimum: 0
        createAt:
          type: string
          format: date
        complete:
          type: boolean
        completionPercentage:
          type: number
          format: float
          maximum: 100.0
        claim:
          $ref: '#/components/schemas/Claim'

    ErrorResponse:
      type: object
      properties:
        code:
          type: integer
          example: 400
        message:
          type: string
          example: "Error en los parametros de la llamada"